### ISSUE TITLE
Why set `posembed=False`?

### ISSUE THREAD

**Issue by thucz** [MzeroMiko/VMamba#290]
Hi! I'm very curious about the parameter `posembed`. Previous methods such as ViTs use positional embedding. But in your method, you set `posembed=False`. Have you done ablation study about this?

**Comment by MzeroMiko** [comment]
I did not. 

I did not use it because I think the positional embedding may prompt the classification performance, but may also affect the ability to accept images with different size. Simply interpolating the positional embedding is clearly a suboptimal solution, so I decided to avoid this problem by omitting it.

**Comment by thucz** [comment]
Thanks for your reply. I get it.
